disabled_rules: #ディフォルトで有効なルールから無視したいもの
- conditional_returns_on_newline

opt_in_rules:
- attributes
- closure_end_indentation
- closure_spacing
- closing-brace-spacing
- closure-parameter-position
- colon
- comma-spacing
- empty-parameters
- empty_count
- explicit_init
- fatal_error_message
- first_where
- force-cast
- force_unwrapping
- force-try
- statement-position
- switch-and-case-statement-alignment
- todo
- unused-optional-binding
- weak-delegate
- implicitly_unwrapped_optional
- number_separator
- object_literal
- operator_usage_whitespace
- overridden_super_call
- private_outlet
- prohibited_super_call
- redundant_nil_coalescing
- switch_case_on_newline
- valid_docs
- trailing_whitespace

excluded:
- Pods/
- Carthage/
- vendor/bundle
- GithubMVVMFlux/Extension

line_length: 300
