disabled_rules: #ディフォルトで有効なルールから無視したいもの
- conditional_returns_on_newline

opt_in_rules:
- attributes
- closure_end_indentation
- closure_spacing
- empty_count
- explicit_init
- fatal_error_message
- first_where
- force_unwrapping
- implicitly_unwrapped_optional
- number_separator
- object_literal
- operator_usage_whitespace
- overridden_super_call
- private_outlet
- prohibited_super_call
- redundant_nil_coalescing
- switch_case_on_newline
- valid_docs
- trailing_whitespace

excluded:
- Pods/
- Carthage/
- vendor/bundle

line_length: 300
