# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
	desc "Run Test"
	lane :test do
		run_tests(devices: ["iPhone 8 Plus"])
  end
  	desc "Run lint autocorrect"
  	lane :lint_autocorrect do
	    swiftlint(
	      mode: :autocorrect,
	      format: true,
	      executable: './Pods/SwiftLint/swiftlint',
	      config_file: '.swiftlint.yml',
	    )
  end
  	desc "Run linting"
	lane :lint do
		swiftlint(
		  executable: './Pods/SwiftLint/swiftlint', 
		  mode: :lint,
		  config_file: '.swiftlint.yml',
		)
  end
  	desc "Update Swiftgen"
  	lane :swiftgen do
  		sh "cd .. && ./Pods/SwiftGen/bin/swiftgen"
  end	
end
